version: "3.9"

services:
  nginx:
    image: ${IMAGE_NAME:-nginx:latest}
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    environment:
      - NGINX_ENV=production
      - APP_NAME=${SERVICE_NAME:-nginx-service}
