name: Deploy Single Service

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-deploy:
    uses: vn-fin/xno_deployment_workflows/.github/workflows/workflow-swarm.yml
  with:
    environment: dev
    services: "root"
