name: Docker Deploy Base

on: 
  push:
    branches:
      - main
  # workflow_call:
  #   inputs:
  #     branch:
  #       required: true
  #       type: string
  #     directory:
  #       required: true
  #       type: string
  #     environment:
  #       required: true
  #       type: string

jobs:
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    # environment: 
    #   name: ${{ inputs.environment }}
    steps:
      - name: Deploy via SSH
        run: |
          echo "[${{ secrets.environment }}] Deploying to server with branch: ${{ inputs.branch }}"
          echo "[${{ secrets.environment }}] Deploying to ${{ secrets.SSH_HOST }} as ${{ secrets.SSH_USERNAME }} on branch ${{ inputs.branch }}"
