name: Docker Deploy Base

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      directory:
        required: false
        type: string
        default: "/home/deploy"

jobs:
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    environment: ${{ inputs.branch }}
    steps:
      - name: Deploy via SSH
        run: |
          echo "Deploying to server with branch: ${{ inputs.branch }}"
          echo "Deploying to ${{ secrets.SSH_HOST }} as ${{ secrets.SSH_USERNAME }} on branch ${{ inputs.branch }}"
          
          echo "${{ secrets.SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem

          cat private_key.pem

          ssh -i private_key.pem -p 24700 ${{ secrets.SSH_HOST }}@${{ secrets.SSH_USERNAME }} << EOF
            set -e
            cd ${{ inputs.directory }} || mkdir -p ${{ inputs.directory }} && cd ${{ inputs.directory }}

            if [ ! -d .git ]; then
              git clone git@github.com:${{ github.repository }} .
            fi

            git fetch origin
            git checkout ${{ inputs.branch }}
            git pull origin ${{ inputs.branch }}

            source ~/.bashrc
            docker compose up -d --build
          EOF
