name: Docker Deploy Base

on: 
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      directory:
        required: true
        type: string
      env_name:
        required: true
        type: string

jobs:
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.env_name }}
    steps:
      - name: Deploy via SSH
        run: |
          echo "[${{ inputs.env_name }}] Deploying to server with branch: ${{ inputs.branch }}"
          echo "[${{ inputs.env_name }}] Deploying to ${{ secrets.SSH_HOST }} as ${{ secrets.SSH_USERNAME }} on branch ${{ inputs.branch }}"
          
