name: Docker Deploy Base

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      directory:
        required: false
        type: string
        default: "/home/deploy"

jobs:
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        run: |

          if [[ "${{ inputs.branch }}" == "deploy-dev" ]]; then
            SSH_HOST=${{ secrets.SSH_DEV_HOST }}
            SSH_USER=${{ secrets.SSH_DEV_USERNAME }}
            SSH_KEY=${{ secrets.SSH_DEV_KEY }}
          elif [[ "${{ inputs.branch }}" == "deploy-prod" ]]; then
            SSH_HOST=${{ secrets.SSH_PROD_HOST }}
            SSH_USER=${{ secrets.SSH_PROD_USERNAME }}
            SSH_KEY=${{ secrets.SSH_PROD_KEY }}
          else
            echo "Unknown branch: ${{ inputs.branch }}"
            exit 1
          fi


          echo "Deploying to $SSH_HOST as $SSH_USER on branch ${{ inputs.branch }}"
          
          echo "$SSH_KEY" > private_key.pem
          chmod 600 private_key.pem

          ssh -o StrictHostKeyChecking=no -i private_key.pem -p 24700 $SSH_HOST@$SSH_USER << EOF
            set -e
            cd ${{ inputs.directory }} || mkdir -p ${{ inputs.directory }} && cd ${{ inputs.directory }}

            if [ ! -d .git ]; then
              git clone git@github.com:${{ github.repository }} .
            fi

            git fetch origin
            git checkout ${{ inputs.branch }}
            git pull origin ${{ inputs.branch }}

            source ~/.bashrc
            docker compose up -d --build
          EOF
