name: Deploy Project

on:
  workflow_call:
    inputs:
      RELEASE_TAG:
        required: true
        type: string
      RELEASE_TITLE:
        required: true
        type: string
    secrets:
      SSH_DEV_KEY:
        required: true
      SSH_DEV_HOST:
        required: true
      SSH_DEV_USERNAME:
        required: true
      SSH_PROD_KEY:
        required: true
      SSH_PROD_HOST:
        required: true
      SSH_PROD_USERNAME:
        required: true

jobs:
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to DEV
        if: contains(inputs.RELEASE_TITLE, 'Deploy Dev')
        run: |
          echo "[dev] Deploying tag ${{ inputs.RELEASE_TAG }}"
          echo "${{ secrets.SSH_DEV_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          mkdir -p ~/.ssh
          ssh-keyscan -p 24700 ${{ secrets.SSH_DEV_HOST }} >> ~/.ssh/known_hosts

          ssh -p 24700 -i private_key.pem ${{ secrets.SSH_DEV_USERNAME }}@${{ secrets.SSH_DEV_HOST }} bash << EOF
            cd /home/deploy
            export PROJECT_NAME=\$(echo ${{ github.repository }} | cut -d'/' -f2)

            if [ ! -d "\$PROJECT_NAME" ]; then
              git clone https://github.com/${{ github.repository }}.git "\$PROJECT_NAME"
            fi

            cd "/home/deploy/\$PROJECT_NAME"
            git fetch origin
            git checkout tags/${{ inputs.RELEASE_TAG }}
            git reset --hard ${{ inputs.RELEASE_TAG }}

            docker compose up -d --build
          EOF

      - name: Deploy to PROD
        if: contains(inputs.RELEASE_TITLE, 'Deploy Prod')
        run: |
          echo "[prod] Deploying tag ${{ inputs.RELEASE_TAG }}"
          echo "${{ secrets.SSH_PROD_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          mkdir -p ~/.ssh
          ssh-keyscan -p 24700 ${{ secrets.SSH_PROD_HOST }} >> ~/.ssh/known_hosts

          ssh -p 24700 -i private_key.pem ${{ secrets.SSH_PROD_USERNAME }}@${{ secrets.SSH_PROD_HOST }} bash << EOF
            cd /home/deploy
            export PROJECT_NAME=\$(echo ${{ github.repository }} | cut -d'/' -f2)

            if [ ! -d "\$PROJECT_NAME" ]; then
              git clone https://github.com/${{ github.repository }}.git "\$PROJECT_NAME"
            fi

            cd "/home/deploy/\$PROJECT_NAME"
            git fetch origin
            git checkout tags/${{ inputs.RELEASE_TAG }}
            git reset --hard ${{ inputs.RELEASE_TAG }}

            docker compose up -d --build
          EOF
