name: Docker Deploy Base

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      directory:
        required: false
        type: string
        default: "/home/deploy"

jobs:
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    needs: docker

    steps:
      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no -p 24700 ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << EOF
            set -e
            cd ${{ inputs.directory }} || mkdir -p ${{ inputs.directory }} && cd ${{ inputs.directory }}

            # Clone the repo if not exists
            if [ ! -d .git ]; then
              git clone git@github.com:${{ github.repository }} .  # Uses SSH to clone
            fi

            # Move to project directory
            cd ${{ inputs.directory }}

            git fetch origin
            git checkout ${{ inputs.branch }}
            git pull origin ${{ inputs.branch }}

            source ~/.bashrc
            docker compose up -d --build
          EOF
