name: Deploy Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: VN-Fin/xno_deployment_workflows/.github/workflows/base-docker-deploy.yml@main
    with:
      branch: ${{ github.ref_name }}
      directory: "/home/deploy/xno_deployment_workflows"
