name: Deploy Hello API — Staging

on:
  push:
    branches: [staging]
  workflow_dispatch:

jobs:
  deploy:
    uses: vn-fin/xno_deployment_workflows/.github/workflows/new-worflow-swarm.yml@main
    with:
      environment: staging
      services: root
      stack: hello
      node_label: "role == worker"
    secrets:
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
