name: Deploy Hello API — Production

on:
  push:
    branches: [prod]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy:
    uses: vn-fin/xno_deployment_workflows/.github/workflows/new-worflow-swarm.yml@main
    with:
      environment: prod
      services: root
      stack: hello
      build_args: |
        EXAMPLE_ARG_01=arg_01
        EXAMPLE_ARG_02=arg_02
      node_label: "role == worker"
    secrets:
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
